### ISSUE TITLE
Chapter 2 Questions

### ISSUE THREAD

**Issue by njlyon0** [NCEAS-Data-Skills/advancedR#2]
Questions from the group on chapter 2 topics

**Comment by njlyon0** [comment]
Can someone explain the main point of  the “Environments” sub-section ([2.5.2](https://adv-r.hadley.nz/names-values.html#env-modify)) of the “Modify-in-place” section?

**Comment by oharac** [comment]
@njlyon0 I think this is something that will become important later when we get to functions (since they reference chapter 10.2.4).  

Generally when you run a function, an alternate universe is spun up (the executing environment of the function), some stuff happens, maybe you return a value to the global or parent environment, and then that alternate universe disappears and anything that happened inside is forgotten ("what happens in Vegas, stays in Vegas").  

But let's say you wanted to be able to run the function again, but with some memory of what happened last time, you could create a separate environment, like `e1` in the chapter, and then let the function act on things within that environment (retrieving values, updating values).  When the function is done, its own executing environment disappears but the environment `e1` you created is still there, still pointing to the same address despite any modifications (modify-in-place), and any changes to the objects within the environment will persist.

Not sure that's exactly what they had in mind, and I doubt I got all the details right, but I suspect that's at least part of the idea.

**Comment by njlyon0** [comment]
Oh that actually makes a lot of sense (and clarifies the use "remember" in the chapter too). I've never even thought to use a function like that--many of my functions create more internal objects than strictly necessary so I'm not sure I'd want to expose those outside of the function alternate universe--but it's an interesting context. Thanks for explaining!!

**Comment by oharac** [comment]
Re: exposing internal objects created within a function, I think you would have to explicitly assign values to the persistent environment (rather than the function default execution environment) - when I tried something like that, I used the `assign()` function (basically the crunchier version of `<-` and `<<-`) to tell R explicitly which environment the object was to be assigned.

**Comment by njlyon0** [comment]
## Closing

We had this meeting so we're good to close this (IMO)
